NONE = 'none'

KEY = 'key'

POINTER = 'pointer'
POINTER_MOUSE = 'mouse'
POINTER_TOUCH = 'touch'
POINTER_PEN = 'pen'

POINTER_KINDS = set([POINTER_MOUSE, POINTER_TOUCH, POINTER_PEN])

SOURCE_TYPES = set([KEY, POINTER, NONE])
